version: '3'

services:
  mongodb:
    container_name: phonebook-mongodb
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: phonebook-service-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    image: phonebook-service-api
    environment:
      - MONGODB_URI=${MONGODB_DOCKER_URI}
      - PORT=${PORT}
    command: npm run start
    volumes:
      - ./dist/:/usr/app/dist/
      - ./package.json:/usr/app/package.json
    ports:
      - "3001:3001"
    links:
      - mongodb
