export enum ErrorTypeEnum {
  NOT_FOUND = 'NOT_FOUND',
  INVALID_PARAM_ERROR = 'INVALID_PARAM_ERROR',
  INVALID_FILTER_ERROR = 'INVALID_FILTER_ERROR',
  MISSING_MANDATORY_PARAM_ERROR = 'MISSING_MANDATORY_PARAM_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
  EMAIL_IS_ALREADY_USE = 'EMAIL_IS_ALREADY_USE',
}
